"""
Explanation Service — spec's "evidence-first GenAI" principle (§3.3, §8.3).

The LLM receives ONLY structured evidence that was already computed
deterministically upstream (risk objects, impact metrics, ranked actions). It
is asked to phrase that evidence clearly — never to invent a prediction, a
number, or a recommendation of its own. If no API key is configured or the
call fails, a deterministic template produces an equivalent plain-language
summary so the demo never breaks on "LLM unavailable" (spec §7.11 mitigation
table).

Backend: Google Gemini (free tier via Google AI Studio).
Get a free key at: https://aistudio.google.com/apikey
Set GEMINI_API_KEY in your .env file to activate live explanations.
Default model: gemini-2.0-flash (fast, free-tier eligible).
"""
from __future__ import annotations

import json
import logging

from core.config import get_settings

logger = logging.getLogger("SkyGuard-X.explanation")

SYSTEM_PROMPT = (
    "You are the Explanation Service inside SkyGuard-X, a real-time decision-support "
    "system. You will be given structured evidence (risk scores, impact metrics, "
    "ranked candidate actions, confidence, model versions) that was already computed "
    "by deterministic models. Write a short (3-5 sentence), plain-language explanation "
    "of the situation and the recommended action for a human operator who must approve "
    "or reject it. Rules: (1) Use ONLY the numbers and facts given to you — never invent "
    "a statistic, a cause, or an outcome that isn't in the evidence. (2) State the "
    "confidence level in plain words. (3) Note that this is a recommendation requiring "
    "human approval, not an automatic action. (4) Do not use markdown headers."
)


def build_evidence_payload(risk_obj, impact_obj, top_action, all_ranked) -> dict:
    return {
        "risk": {
            "entity_id": risk_obj.entity_id,
            "risk_type": risk_obj.risk_type,
            "risk_score": risk_obj.risk_score,
            "confidence": risk_obj.confidence,
            "status": risk_obj.status,
            "top_evidence": risk_obj.top_evidence,
            "model_version": risk_obj.model_version,
        },
        "impact": {
            "affected_population": impact_obj.affected_population,
            "affected_roads": impact_obj.affected_roads,
            "accessibility_index": impact_obj.accessibility_index,
        } if impact_obj else None,
        "recommended_action": {
            "action_id": top_action.action_id,
            "action_type": top_action.action_type,
            "score": top_action.score,
            "allowed": top_action.allowed,
        } if top_action else None,
        "alternatives_considered": [
            {"action_id": r.action_id, "action_type": r.action_type, "score": r.score, "allowed": r.allowed}
            for r in all_ranked
        ] if all_ranked else [],
    }


def _deterministic_fallback(evidence: dict) -> str:
    risk = evidence.get("risk") or {}
    impact = evidence.get("impact")
    action = evidence.get("recommended_action")

    parts = [
        f"{risk.get('entity_id', 'The monitored entity')} shows {risk.get('status', 'an')} "
        f"{risk.get('risk_type', 'risk')} risk (score {risk.get('risk_score')}, "
        f"confidence {risk.get('confidence')})."
    ]
    if risk.get("top_evidence"):
        parts.append("Contributing factors: " + ", ".join(risk["top_evidence"]) + ".")
    if impact:
        parts.append(
            f"Estimated impact: {impact['affected_population']} people and "
            f"{len(impact['affected_roads'])} road segment(s) affected, "
            f"road accessibility index {impact['accessibility_index']}."
        )
    if action:
        status = "recommended" if action["allowed"] else "blocked by a hard safety/authorization constraint"
        parts.append(
            f"Action '{action['action_type']}' (id {action['action_id']}) is {status}, "
            f"score {action['score']}. This is a recommendation and requires human approval "
            f"before any action is taken."
        )
    parts.append(f"(Generated by deterministic template — model_version={risk.get('model_version')}.)")
    return " ".join(parts)


def generate_explanation(evidence: dict) -> dict:
    """Returns {"text": ..., "mode": "llm"|"template", "model": ...}.

    Uses Google Gemini if GEMINI_API_KEY is set (free tier available at
    https://aistudio.google.com/apikey). Falls back gracefully to a
    deterministic template if the key is absent or the API call fails.
    """
    settings = get_settings()

    if not settings.gemini_api_key:
        return {"text": _deterministic_fallback(evidence), "mode": "template", "model": None}

    try:
        import google.generativeai as genai  # local import: optional dependency

        genai.configure(api_key=settings.gemini_api_key)
        model = genai.GenerativeModel(
            model_name=settings.explanation_model,
            system_instruction=SYSTEM_PROMPT,
        )
        response = model.generate_content(
            json.dumps(evidence),
            generation_config=genai.types.GenerationConfig(max_output_tokens=400),
        )
        text = response.text.strip()
        return {"text": text, "mode": "llm", "model": settings.explanation_model}

    except Exception as exc:  # LLM unavailable -> fail-safe, never blocks the decision loop
        logger.warning("Gemini explanation failed, falling back to template: %s", exc)
        return {"text": _deterministic_fallback(evidence), "mode": "template_fallback", "model": None}
